---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror通过 LAN 或 WAN 高速复制数据，因此您可以在虚拟和传统环境中获得高数据可用性和快速数据复制。当您将数据复制到NetApp存储系统并不断更新辅助数据时，您的数据将保持最新状态并在您需要时保持可用。不需要外部复制服务器。 
---
= 了解NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror通过 LAN 或 WAN 高速复制数据，因此您可以在虚拟和传统环境中获得高数据可用性和快速数据复制。当您使用NetApp Replication将数据复制到NetApp存储系统并不断更新二级数据时，您的数据将保持最新状态并在您需要时保持可用。不需要外部复制服务器。



[[netapp-console]]
== NetApp Console

可以通过NetApp Console访问NetApp Replication 。

控制台在企业级层面跨本地和云环境提供 NetApp 存储和数据服务的集中管理。访问和使用 NetApp 数据服务需要控制台 (Console)。作为管理界面，它使您能够从一个界面管理多个存储资源。控制台管理员可以控制企业内所有系统对存储和服务的访问。

您无需许可证或订阅即可开始使用控制台。仅当需要在云中部署控制台代理以确保与存储系统或 NetApp 数据服务的连接时，才会产生费用。但是，从控制台访问的某些 NetApp 数据服务是基于许可证或订阅的。

详细了解 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"]。



[[features]]
== 功能

* 在ONTAP存储系统之间复制数据，以支持到云或云之间的备份和灾难恢复。
* 通过高可用性确保您的 DR 环境的可靠性。
* ONTAP 存储系统之间的高效块级复制快速高效，具有用于灾难恢复和备份的精细恢复点。




[[cost]]
== 成本

NetApp不会向您收取使用NetApp Replication 的费用，但您需要向您的云提供商查询适用的数据入口和出口费用。



[[supported-systems]]
== 支持的系统

NetApp Replication支持以下类型的系统之间的数据复制。

[cols="30,30"]
|===
| 源系统 | 支持的目标系统 


| Cloud Volumes ONTAP  a| 
* 适用于ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 本地 ONTAP 集群




| 本地 ONTAP 集群  a| 
* 适用于ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 本地 ONTAP 集群




| 适用于ONTAP 的Amazon FSx  a| 
* 适用于ONTAP 的Amazon FSx
* Cloud Volumes ONTAP
* 本地 ONTAP 集群


|===


[[how-data-replication-works]]
== 数据复制的工作原理

NetApp Replication 使用 SnapMirror 和 SnapVault 技术简化了不同 ONTAP 系统上的卷之间的数据复制。要配置复制，只需标识源卷和目标卷，然后选择复制策略和计划。

对于Cloud Volumes ONTAP， NetApp Replication会购买所需的磁盘、配置关系、应用复制策略，然后启动卷之间的基线传输。


NOTE: 基线传输包括源数据的完整副本。后续传输包含源数据的差异副本。



[[supported-data-protection-configurations]]
== 支持的数据保护配置

NetApp Replication支持简单、扇出和级联数据保护配置：

* 在简单的配置中，复制从卷 A 发生到卷 B。
* 在扇出配置中，复制从卷 A 发生到多个目标。
* 在级联配置中，复制从卷 A 发生到卷 B，再从卷 B 发生到卷 C。




[[replicate-data-using-netapp-backup-and-recovery]]
== 使用NetApp Backup and Recovery复制数据

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^] 使您能够在单独的 ONTAP 系统上的卷之间复制数据，同时还可以将相同的数据备份到对象存储。如果要在单个服务中同时管理相同 ONTAP 数据的复制和备份到对象保护，请考虑使用 NetApp Backup and Recovery。

NetApp Replication 支持以下在 Backup and Recovery 中不可用的功能。

* Backup and Recovery 当前不支持将数据复制到 FSx for ONTAP 系统或从 FSx for ONTAP 系统复制数据。
* Backup and Recovery 不支持创建卷的一次性复制。


此外，在 Replication 中更容易配置级联关系。如果需要上述任何功能，请使用 NetApp Replication。
